-- DatabaseScripts/002_SeedData.sql
-- Seed Data for Toyota Vehicle Service Tracker
-- Password: Toyota2024!
-- Hash will be generated by application

-- Admin User (automatically created by application on first run)
-- Username: admin
-- Password: Toyota2024!
-- Full Name: System Administrator

-- Sample Service Entries for Testing
INSERT INTO service_entries (
    id, 
    license_plate, 
    brand_name, 
    model_name, 
    kilometers, 
    model_year, 
    service_date, 
    has_warranty, 
    service_city, 
    service_note,
    created_at
) VALUES 
    (
        gen_random_uuid(),
        '34ABC123',
        'Toyota',
        'Corolla',
        45000,
        2020,
        '2024-10-15'::timestamp with time zone,
        true,
        'İstanbul',
        'Periyodik bakım yapıldı. Motor yağı ve filtreler değiştirildi.',
        now()
    ),
    (
        gen_random_uuid(),
        '06XYZ789',
        'Toyota',
        'Camry',
        78000,
        2019,
        '2024-10-10'::timestamp with time zone,
        true,
        'Ankara',
        'Fren balata değişimi yapıldı. Genel kontrol tamamlandı.',
        now()
    ),
    (
        gen_random_uuid(),
        '35DEF456',
        'Toyota',
        'RAV4',
        32000,
        2022,
        '2024-10-05'::timestamp with time zone,
        true,
        'İzmir',
        'İlk servis bakımı. Garantili parça değişimi yapıldı.',
        now()
    ),
    (
        gen_random_uuid(),
        '07GHI321',
        'Toyota',
        'Prius',
        67000,
        2018,
        '2024-09-28'::timestamp with time zone,
        false,
        'Bursa',
        'Hibrit sistem kontrolü ve güncelleme yapıldı.',
        now()
    ),
    (
        gen_random_uuid(),
        '16JKL654',
        'Toyota',
        'Yaris',
        25000,
        2023,
        '2024-10-01'::timestamp with time zone,
        true,
        'Antalya',
        'Rutin bakım ve kontrol işlemleri tamamlandı.',
        now()
    )
ON CONFLICT (id) DO NOTHING;